export class RestPkiClient {
    constructor(endpointUrl: any, accessToken?: null, proxy?: null);
    _endpointUrl: any;
    _accessToken: any;
    _proxy: any;
    _multipartUploadThreshold: number;
    _multipartUploadDoubleCheck: boolean;
    _timeout: number;
    getTimeoutInMin(): number;
    getTimeoutInSec(): number;
    setTimeoutInMin(value: any): void;
    setTimeoutInSec(value: any): void;
    getRestPkiVersion(): any;
    setRestPkiVersion(restPkiVersion: any): void;
    _restPkiVersion: any;
    getEndpointUrl(): any;
    getAccessToken(): any;
    getProxy(): any;
    getMultipartUploadThreshold(): number;
    getMultipartUploadDoubleCheck(): boolean;
    setEndpointUrl(value: any): void;
    setAccessToken(value: any): void;
    setProxy(value: any): void;
    setMultipartUploadThreshold(value: any): void;
    setMultipartUploadDoubleCheck(value: any): void;
    set endpointUrl(value: any);
    get endpointUrl(): any;
    set accessToken(value: any);
    get accessToken(): any;
    set proxy(value: any);
    get proxy(): any;
    set multipartUploadThreshold(value: number);
    get multipartUploadThreshold(): number;
    set multipartUploadDoubleCheck(value: boolean);
    get multipartUploadDoubleCheck(): boolean;
    set restPkiVersion(value: any);
    get restPkiVersion(): any;
    getRestClient(): RestClient;
    getAuthentication(): Authentication;
    _uploadOrRead(stream: any): Promise<any>;
    _read(stream: any): Promise<any>;
    _upload(stream: any): Promise<any>;
    _uploadParts(stream: any, client: any, blobUri: any, partSize: any): Promise<any>;
    uploadFileFromPath(path: any): Promise<any>;
    uploadFileFromStream(stream: any): Promise<any>;
    uploadFileFromContent(content: any): Promise<any>;
    getApiVersion(api: any): 1 | 0 | 3 | 2 | Promise<1 | 0 | 3 | 2>;
    _getApiVersion(api: any, v: any): 1 | 0 | 3 | 2;
    _tryGetEndpointVersion(endpoint: any): Promise<ApiVersion>;
}
import { ApiVersion } from "./api-version";
import { Authentication } from "./authentication";
import { RestClient } from "./rest-client";

